# Documentation : https://github.com/Azure/webapps-deploy
name: Build and deploy Node.js app to Azure Web App - brefle-traveldb

on:
  push:
    branches:
      - azure-deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js version
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './backend/package-lock.json'

      - name: Build Backend (AdonisJS)
        # On se place dans le dossier backend comme spécifié dans deploy.yml
        working-directory: ./backend 
        run: |
          npm ci
          # Installation du compilateur SWC nécessaire pour le build AdonisJS sur Linux
          npm install @swc/core-linux-x64-gnu --no-save
          npm run build

      - name: Prepare Production Artifact
        # Azure a besoin du package.json à la racine de l'artéfact pour identifier le point d'entrée
        run: |
          cp backend/package.json backend/build/
          cp backend/package-lock.json backend/build/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend/build/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'brefle-traveldb'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D6931BD24C14431B97957C2AEB8D01DA }}