name: Build and deploy to Azure (Full Stack)

on:
  push:
    branches:
      - azure-deploy
  workflow_dispatch:

jobs:
  # --- JOB 1 : BACKEND (Azure App Service) ---
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Build Backend (AdonisJS)
        working-directory: ./backend
        run: |
          npm ci
          npm install @swc/core-linux-x64-gnu --no-save
          npm run build

      - name: Prepare Artifact
        run: |
          cp backend/package.json backend/build/
          cp package-lock.json backend/build/

      - name: 'Deploy Backend to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'brefle-traveldb'
          # Utilise ton secret App Service existant
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D6931BD24C14431B97957C2AEB8D01DA }}
          package: backend/build/

            # --- JOB 2 : FRONTEND (Azure Static Web Apps) ---
